### ISSUE TITLE
[EasyDecision] Some decision stuck to its previous output

### ISSUE THREAD

**Issue by jayaregalinadaflexisourceit** [eonx-com/easy-monorepo#722] opened 2021-09-09 09:46 UTC
**Describe the bug**

Some decision like `AffirmativeDecision` seems to stuck their previous `$this->output` value. Like in `AffirmativeDecision`, if the `$this->output` already have a value `true` on its previous state, then rest will be `true`.

**To Reproduce**

1. Create a custom Rule
2. Create a custom Configurator and inject the Rule (from Step 1)
3. Create a class/service that uses `DecisionInterface` via [factory injection](https://symfony.com/doc/current/service_container/factories.html) (from Step 2)
4. Loop and validate tru this class/service (from Step 3) with 2 valid and 1 invalid value based on Rule (from Step 1)
5. Make sure the 1 invalid value should be in between the 2 valid values to see the effect, either in the middle or at the very first loop
6. Created a simple app https://github.com/jayaregalinadaflexisourceit/easy-decision-poc-test

**Expected behavior**

- From the above **To Reproduce** on Step 4, even if the first value is invalid, the rest will should still be valid and accepted from the decision. 
- From the simple app I created (on Step 6) if you go to `/instrument` endpoint, there should be 3 instruments created

**Additional context**
- I copy-paste the `AffirmativeDecision` from the package.
- I also created a work around for `AbstractDecision::getContext()` to avoid throwing `ContextNotSetException`. See Issue #721

**Comment by natepage** [comment] 2021-09-09 15:24
@jayaregalinadaflexisourceit amazing issue! And thank you for taking the time to create the app to reproduce the problem.

You are correct, the decisions classes were not smart enough to reset their default output, I think that it wasn't intended for a decision to be used more than once from the start. But it wasn't a big change to make it possible, so the new release `3.3.11` makes sure that each decision reset its output before each run.

Please let me know if it fixes your issue.

**Comment by natepage** [comment] 2021-09-13 04:53
Was fixed in https://github.com/eonx-com/easy-monorepo/releases/tag/3.3.11, feel free to re-open if the issue persisted.

**Closed by natepage** 2021-09-13 04:53 UTC
